#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CirclerProgressQs.Resource", IsApplication=true)]

namespace CirclerProgressQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010029
			public const int arcProgressStyle = 2130772009;
			
			// aapt resource value: 0x7f010001
			public const int arc_angle = 2130771969;
			
			// aapt resource value: 0x7f01000b
			public const int arc_bottom_text = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int arc_bottom_text_size = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int arc_finished_color = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int arc_max = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int arc_progress = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int arc_stroke_width = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int arc_suffix_text = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int arc_suffix_text_padding = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int arc_suffix_text_size = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int arc_text_color = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int arc_text_size = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int arc_unfinished_color = 2130771972;
			
			// aapt resource value: 0x7f010027
			public const int circleProgressStyle = 2130772007;
			
			// aapt resource value: 0x7f010010
			public const int circle_finished_color = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int circle_max = 2130771982;
			
			// aapt resource value: 0x7f010013
			public const int circle_prefix_text = 2130771987;
			
			// aapt resource value: 0x7f01000d
			public const int circle_progress = 2130771981;
			
			// aapt resource value: 0x7f010014
			public const int circle_suffix_text = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int circle_text_color = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int circle_text_size = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int circle_unfinished_color = 2130771983;
			
			// aapt resource value: 0x7f010028
			public const int donutProgressStyle = 2130772008;
			
			// aapt resource value: 0x7f010020
			public const int donut_background_color = 2130772000;
			
			// aapt resource value: 0x7f010024
			public const int donut_circle_starting_degree = 2130772004;
			
			// aapt resource value: 0x7f010018
			public const int donut_finished_color = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int donut_finished_stroke_width = 2130771993;
			
			// aapt resource value: 0x7f010021
			public const int donut_inner_bottom_text = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int donut_inner_bottom_text_color = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int donut_inner_bottom_text_size = 2130772002;
			
			// aapt resource value: 0x7f010026
			public const int donut_inner_drawable = 2130772006;
			
			// aapt resource value: 0x7f010016
			public const int donut_max = 2130771990;
			
			// aapt resource value: 0x7f01001d
			public const int donut_prefix_text = 2130771997;
			
			// aapt resource value: 0x7f010015
			public const int donut_progress = 2130771989;
			
			// aapt resource value: 0x7f010025
			public const int donut_show_text = 2130772005;
			
			// aapt resource value: 0x7f01001e
			public const int donut_suffix_text = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int donut_text = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int donut_text_color = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int donut_text_size = 2130771995;
			
			// aapt resource value: 0x7f010017
			public const int donut_unfinished_color = 2130771991;
			
			// aapt resource value: 0x7f01001a
			public const int donut_unfinished_stroke_width = 2130771994;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int nx_logo_green = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ArcProgress = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int ArcProgress_arc_angle = 1;
			
			// aapt resource value: 11
			public const int ArcProgress_arc_bottom_text = 11;
			
			// aapt resource value: 12
			public const int ArcProgress_arc_bottom_text_size = 12;
			
			// aapt resource value: 5
			public const int ArcProgress_arc_finished_color = 5;
			
			// aapt resource value: 3
			public const int ArcProgress_arc_max = 3;
			
			// aapt resource value: 0
			public const int ArcProgress_arc_progress = 0;
			
			// aapt resource value: 2
			public const int ArcProgress_arc_stroke_width = 2;
			
			// aapt resource value: 8
			public const int ArcProgress_arc_suffix_text = 8;
			
			// aapt resource value: 10
			public const int ArcProgress_arc_suffix_text_padding = 10;
			
			// aapt resource value: 9
			public const int ArcProgress_arc_suffix_text_size = 9;
			
			// aapt resource value: 7
			public const int ArcProgress_arc_text_color = 7;
			
			// aapt resource value: 6
			public const int ArcProgress_arc_text_size = 6;
			
			// aapt resource value: 4
			public const int ArcProgress_arc_unfinished_color = 4;
			
			public static int[] CircleProgress = new int[] {
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 3
			public const int CircleProgress_circle_finished_color = 3;
			
			// aapt resource value: 1
			public const int CircleProgress_circle_max = 1;
			
			// aapt resource value: 6
			public const int CircleProgress_circle_prefix_text = 6;
			
			// aapt resource value: 0
			public const int CircleProgress_circle_progress = 0;
			
			// aapt resource value: 7
			public const int CircleProgress_circle_suffix_text = 7;
			
			// aapt resource value: 5
			public const int CircleProgress_circle_text_color = 5;
			
			// aapt resource value: 4
			public const int CircleProgress_circle_text_size = 4;
			
			// aapt resource value: 2
			public const int CircleProgress_circle_unfinished_color = 2;
			
			public static int[] DonutProgress = new int[] {
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 11
			public const int DonutProgress_donut_background_color = 11;
			
			// aapt resource value: 15
			public const int DonutProgress_donut_circle_starting_degree = 15;
			
			// aapt resource value: 3
			public const int DonutProgress_donut_finished_color = 3;
			
			// aapt resource value: 4
			public const int DonutProgress_donut_finished_stroke_width = 4;
			
			// aapt resource value: 12
			public const int DonutProgress_donut_inner_bottom_text = 12;
			
			// aapt resource value: 14
			public const int DonutProgress_donut_inner_bottom_text_color = 14;
			
			// aapt resource value: 13
			public const int DonutProgress_donut_inner_bottom_text_size = 13;
			
			// aapt resource value: 17
			public const int DonutProgress_donut_inner_drawable = 17;
			
			// aapt resource value: 1
			public const int DonutProgress_donut_max = 1;
			
			// aapt resource value: 8
			public const int DonutProgress_donut_prefix_text = 8;
			
			// aapt resource value: 0
			public const int DonutProgress_donut_progress = 0;
			
			// aapt resource value: 16
			public const int DonutProgress_donut_show_text = 16;
			
			// aapt resource value: 9
			public const int DonutProgress_donut_suffix_text = 9;
			
			// aapt resource value: 10
			public const int DonutProgress_donut_text = 10;
			
			// aapt resource value: 7
			public const int DonutProgress_donut_text_color = 7;
			
			// aapt resource value: 6
			public const int DonutProgress_donut_text_size = 6;
			
			// aapt resource value: 2
			public const int DonutProgress_donut_unfinished_color = 2;
			
			// aapt resource value: 5
			public const int DonutProgress_donut_unfinished_stroke_width = 5;
			
			public static int[] Themes = new int[] {
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 2
			public const int Themes_arcProgressStyle = 2;
			
			// aapt resource value: 0
			public const int Themes_circleProgressStyle = 0;
			
			// aapt resource value: 1
			public const int Themes_donutProgressStyle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
